import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import RQProvider from "@/components/providers/rq-provider";
import { NextAuthProviders } from "@/components/providers/auth-provider";
import { SiteHeader } from "@/components/client/panel/site-header";
import ClientLayout from "@/components/client/panel/client-layout";
import { SigninDialog } from "@/components/auth/signin/signin-dialog";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <NextAuthProviders>
        <RQProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            suppressHydrationWarning
          >
            <SigninDialog />
            <ClientLayout>{children}</ClientLayout>
            <Toaster />
          </body>
        </RQProvider>
      </NextAuthProviders>
    </html>
  );
}
